import os

DEFAULT_CTX         = 16384
DEFAULT_CLOUD_CTX   = 131072  # 128k token
DEFAULT_MAX_TOKENS  = 16384
DEFAULT_TEMPERATURE = 0.3
DEFAULT_TOP_P       = 0.95
CPU_COUNT           = os.cpu_count() or 8
DEFAULT_N_THREADS   = max(4, min(16, CPU_COUNT - 1))
DEFAULT_N_BATCH     = min(DEFAULT_CTX, 2048)
DEFAULT_N_UBATCH    = min(DEFAULT_N_BATCH, 512)
THINKING_SHIMMER_INTERVAL = 0.09
THINKING_SHIMMER_STEP = 5.0
THINKING_PHRASE_SWAP_EVERY = 72
CLOUD_REQUESTS_PER_MINUTE = 15
CLOUD_REQUEST_MIN_INTERVAL = 4.25

TAVILY_API_KEY         = ""

